# Generated by Django 4.0.2 on 2022-10-12 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2c77bcd6-4184-4434-83aa-118a90f86bb0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
