# Generated by Django 4.0.2 on 2022-10-13 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_todo_user_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1cf70d69-b18a-4395-ae6b-e5664e6122fd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1cf70d69-b18a-4395-ae6b-e5664e6122fd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
