# Generated by Django 4.0 on 2022-04-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_types', models.CharField(max_length=50)),
                ('product_types_img', models.ImageField(upload_to='type_img')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products_Name', models.CharField(max_length=50)),
                ('Products_Image', models.ImageField(upload_to='products_img')),
                ('Products_quantity', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(auto_now_add=True)),
                ('Products_base_price', models.BigIntegerField()),
                ('Products_selling_price', models.BigIntegerField()),
                ('ProductType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.producttype')),
            ],
        ),
    ]
