# Generated by Django 4.0 on 2022-04-25 08:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('admin_panel', '0003_alter_comapany_details_company_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers_name', models.CharField(max_length=15)),
                ('suppliers_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('suppliers_goods', models.CharField(max_length=15)),
                ('gst_number', models.CharField(max_length=15)),
                ('business_number', models.CharField(max_length=15)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='products_details',
            name='suppliers_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.suppliers'),
            preserve_default=False,
        ),
    ]
