# Generated by Django 4.1.2 on 2022-10-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_remove_task_user_alter_task_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Complete_date',
            field=models.DateField(auto_now=True),
        ),
    ]
