# Generated by Django 4.1.2 on 2022-10-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='User',
        ),
    ]
