# Generated by Django 4.1.2 on 2022-10-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete_time',
        ),
        migrations.AddField(
            model_name='task',
            name='Status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Completed', 'Completed')], default='On Going', max_length=10),
        ),
    ]
