# Generated by Django 4.0 on 2022-04-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('admin_panel', '0004_suppliers_products_details_suppliers_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_price', models.BigIntegerField()),
                ('Product_quantity', models.BigIntegerField()),
                ('Profit', models.BigIntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=50)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.products_details')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
