# Generated by Django 4.0 on 2022-04-27 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='Customer_Name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotations',
            name='Custumer_contact',
            field=models.CharField(default=45, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotations',
            name='Profit',
            field=models.BigIntegerField(default=0),
        ),
    ]
